In [320]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [321]:
df = pd.read_csv("homeprices.csv")

In [322]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [323]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [324]:
df['bedrooms'].median()

4.0

In [325]:
df=df.fillna(df['bedrooms'].median())

In [326]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [327]:
from sklearn import linear_model

In [328]:
reg = linear_model.LinearRegression()

In [329]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [330]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [331]:
reg.intercept_

221323.00186540408

In [332]:
reg.predict([[3300,4,18]])

array([626513.65823081])

In [333]:
a = 3300*119.67905405+4*13097.24903475+18*-4207.28764479+256461.14864864887

In [334]:
a

628059.8455464288

# Example Testing

In [338]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
%matplotlib inline

In [339]:
df = pd.read_csv("hiring.csv",names=['experience','test_score','interview_score','salary'])

In [340]:
df.drop(index=0,inplace=True)

In [341]:
df['experience']=df['experience'].fillna(1)

In [342]:
names={'five':5,'two':2,'seven':7,'three':3,'ten':10,'eleven':11}

In [343]:
df['test_score']=df.test_score.fillna(df['test_score'].median())

In [344]:
df

experience test_score interview_score salary
1          1          8               9  50000
2          1          8               6  45000
3       five          6               7  60000
4        two         10              10  65000
5      seven          9               6  70000
6      three          7              10  62000
7        ten          8               7  72000
8     eleven          7               8  80000

In [345]:
df['experience'].iloc[7]

'eleven'

In [346]:
df['experience'].iloc[7]

'eleven'

In [347]:
for i in range(2,8):
    #print(names[df['experience'].iloc[i]])
    #if names[df['experience'].iloc[i]].notnull():
    df['experience'].iloc[i]=names[df['experience'].iloc[i]]
    

In [348]:
df

experience test_score interview_score salary
1           1          8               9  50000
2           1          8               6  45000
3           5          6               7  60000
4           2         10              10  65000
5           7          9               6  70000
6           3          7              10  62000
7          10          8               7  72000
8          11          7               8  80000

In [349]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8 entries, 1 to 8
Data columns (total 4 columns):
experience         8 non-null int64
test_score         8 non-null object
interview_score    8 non-null object
salary             8 non-null object
dtypes: int64(1), object(3)
memory usage: 224.0+ bytes


In [350]:
from sklearn import linear_model

In [351]:
reg=linear_model.LinearRegression()

In [352]:
df

experience test_score interview_score salary
1           1          8               9  50000
2           1          8               6  45000
3           5          6               7  60000
4           2         10              10  65000
5           7          9               6  70000
6           3          7              10  62000
7          10          8               7  72000
8          11          7               8  80000

In [353]:
reg.fit(df.drop('salary',axis=1),df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [354]:
reg.coef_

array([3031.1979513 , 1893.22650937, 2485.73083785])

In [355]:
reg.intercept_

13359.721134159729

In [356]:
reg.predict([[2,9,6]])

array([51375.54064819])

In [357]:
reg.predict([[12,10,10]])

array([93523.67002192])